// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.5.0
// source: kvdb.proto

package kvobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValLen    int32  `protobuf:"varint,1,opt,name=valLen,proto3" json:"valLen,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ExpiredAt int64  `protobuf:"varint,3,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
}

func (x *KvMeta) Reset() {
	*x = KvMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvMeta) ProtoMessage() {}

func (x *KvMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvMeta.ProtoReflect.Descriptor instead.
func (*KvMeta) Descriptor() ([]byte, []int) {
	return file_kvdb_proto_rawDescGZIP(), []int{0}
}

func (x *KvMeta) GetValLen() int32 {
	if x != nil {
		return x.ValLen
	}
	return 0
}

func (x *KvMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KvMeta) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type KvEvictItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *KvEvictItem) Reset() {
	*x = KvEvictItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KvEvictItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvEvictItem) ProtoMessage() {}

func (x *KvEvictItem) ProtoReflect() protoreflect.Message {
	mi := &file_kvdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvEvictItem.ProtoReflect.Descriptor instead.
func (*KvEvictItem) Descriptor() ([]byte, []int) {
	return file_kvdb_proto_rawDescGZIP(), []int{1}
}

func (x *KvEvictItem) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_kvdb_proto protoreflect.FileDescriptor

var file_kvdb_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x76, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x06,
	0x4b, 0x76, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x4c, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x21, 0x0a, 0x0b, 0x4b, 0x76, 0x45, 0x76, 0x69, 0x63, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6b, 0x76, 0x6f, 0x62, 0x6a, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kvdb_proto_rawDescOnce sync.Once
	file_kvdb_proto_rawDescData = file_kvdb_proto_rawDesc
)

func file_kvdb_proto_rawDescGZIP() []byte {
	file_kvdb_proto_rawDescOnce.Do(func() {
		file_kvdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_kvdb_proto_rawDescData)
	})
	return file_kvdb_proto_rawDescData
}

var file_kvdb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kvdb_proto_goTypes = []interface{}{
	(*KvMeta)(nil),      // 0: KvMeta
	(*KvEvictItem)(nil), // 1: KvEvictItem
}
var file_kvdb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kvdb_proto_init() }
func file_kvdb_proto_init() {
	if File_kvdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kvdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KvEvictItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kvdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kvdb_proto_goTypes,
		DependencyIndexes: file_kvdb_proto_depIdxs,
		MessageInfos:      file_kvdb_proto_msgTypes,
	}.Build()
	File_kvdb_proto = out.File
	file_kvdb_proto_rawDesc = nil
	file_kvdb_proto_goTypes = nil
	file_kvdb_proto_depIdxs = nil
}
