defaultPort: 9003

nodeName: testNode
nodeHost: 127.0.0.1
msgStoreEngine: mysql 

log:
  logPath: ./logs
  logName: jim-info

kvdb:
  isOpen: true

mysql:
  user: root
  password: 123456
  address: 127.0.0.1:3306
  name: im_db

mongodb:
  address: 127.0.0.1:27017
  name: jim_msgs

apiGateway:
  httpPort: 9001

connectManager:
  wsPort: 9003

adminGateway:
  httpPort: 8090

imApiDomain: http://127.0.0.1:8082