ALTER TABLE `ioscertificates`
  ADD COLUMN `auth_type` VARCHAR(8) NOT NULL DEFAULT 'p12',
  ADD COLUMN `p8_key_id` VARCHAR(32) NOT NULL DEFAULT '',
  ADD COLUMN `p8_team_id` VARCHAR(32) NOT NULL DEFAULT '',
  ADD COLUMN `p8_private_key` BLOB NULL,
  ADD COLUMN `p8_key_name` VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN `config_version` BIGINT NOT NULL DEFAULT 1;
