// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: commons/pbdefines/converconf.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConverConf struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActivedRtcRoom *ActivedRtcRoom        `protobuf:"bytes,1,opt,name=activedRtcRoom,proto3" json:"activedRtcRoom,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConverConf) Reset() {
	*x = ConverConf{}
	mi := &file_commons_pbdefines_converconf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConverConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConverConf) ProtoMessage() {}

func (x *ConverConf) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_converconf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConverConf.ProtoReflect.Descriptor instead.
func (*ConverConf) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_converconf_proto_rawDescGZIP(), []int{0}
}

func (x *ConverConf) GetActivedRtcRoom() *ActivedRtcRoom {
	if x != nil {
		return x.ActivedRtcRoom
	}
	return nil
}

type ActivedRtcRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomType      RtcRoomType            `protobuf:"varint,1,opt,name=roomType,proto3,enum=RtcRoomType" json:"roomType,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Owner         *UserInfo              `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	RtcChannel    RtcChannel             `protobuf:"varint,4,opt,name=rtcChannel,proto3,enum=RtcChannel" json:"rtcChannel,omitempty"`
	RtcMediaType  RtcMediaType           `protobuf:"varint,5,opt,name=rtcMediaType,proto3,enum=RtcMediaType" json:"rtcMediaType,omitempty"`
	Ext           string                 `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	Members       []*RtcMember           `protobuf:"bytes,51,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivedRtcRoom) Reset() {
	*x = ActivedRtcRoom{}
	mi := &file_commons_pbdefines_converconf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivedRtcRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivedRtcRoom) ProtoMessage() {}

func (x *ActivedRtcRoom) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_converconf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivedRtcRoom.ProtoReflect.Descriptor instead.
func (*ActivedRtcRoom) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_converconf_proto_rawDescGZIP(), []int{1}
}

func (x *ActivedRtcRoom) GetRoomType() RtcRoomType {
	if x != nil {
		return x.RoomType
	}
	return RtcRoomType_OneOne
}

func (x *ActivedRtcRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ActivedRtcRoom) GetOwner() *UserInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ActivedRtcRoom) GetRtcChannel() RtcChannel {
	if x != nil {
		return x.RtcChannel
	}
	return RtcChannel_Zego
}

func (x *ActivedRtcRoom) GetRtcMediaType() RtcMediaType {
	if x != nil {
		return x.RtcMediaType
	}
	return RtcMediaType_RtcAudio
}

func (x *ActivedRtcRoom) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ActivedRtcRoom) GetMembers() []*RtcMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ConverConfReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConverId      string                 `protobuf:"bytes,1,opt,name=converId,proto3" json:"converId,omitempty"`
	ChannelType   ChannelType            `protobuf:"varint,2,opt,name=channelType,proto3,enum=ChannelType" json:"channelType,omitempty"`
	SubChannel    string                 `protobuf:"bytes,3,opt,name=subChannel,proto3" json:"subChannel,omitempty"`
	ConverConf    *ConverConf            `protobuf:"bytes,4,opt,name=converConf,proto3" json:"converConf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConverConfReq) Reset() {
	*x = ConverConfReq{}
	mi := &file_commons_pbdefines_converconf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConverConfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConverConfReq) ProtoMessage() {}

func (x *ConverConfReq) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_converconf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConverConfReq.ProtoReflect.Descriptor instead.
func (*ConverConfReq) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_converconf_proto_rawDescGZIP(), []int{2}
}

func (x *ConverConfReq) GetConverId() string {
	if x != nil {
		return x.ConverId
	}
	return ""
}

func (x *ConverConfReq) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_Unknown
}

func (x *ConverConfReq) GetSubChannel() string {
	if x != nil {
		return x.SubChannel
	}
	return ""
}

func (x *ConverConfReq) GetConverConf() *ConverConf {
	if x != nil {
		return x.ConverConf
	}
	return nil
}

var File_commons_pbdefines_converconf_proto protoreflect.FileDescriptor

const file_commons_pbdefines_converconf_proto_rawDesc = "" +
	"\n" +
	"\"commons/pbdefines/converconf.proto\x1a#commons/pbdefines/appmessages.proto\x1a\x1fcommons/pbdefines/rtcroom.proto\"E\n" +
	"\n" +
	"ConverConf\x127\n" +
	"\x0eactivedRtcRoom\x18\x01 \x01(\v2\x0f.ActivedRtcRoomR\x0eactivedRtcRoom\"\x8b\x02\n" +
	"\x0eActivedRtcRoom\x12(\n" +
	"\broomType\x18\x01 \x01(\x0e2\f.RtcRoomTypeR\broomType\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\x05owner\x18\x03 \x01(\v2\t.UserInfoR\x05owner\x12+\n" +
	"\n" +
	"rtcChannel\x18\x04 \x01(\x0e2\v.RtcChannelR\n" +
	"rtcChannel\x121\n" +
	"\frtcMediaType\x18\x05 \x01(\x0e2\r.RtcMediaTypeR\frtcMediaType\x12\x10\n" +
	"\x03ext\x18\x06 \x01(\tR\x03ext\x12$\n" +
	"\amembers\x183 \x03(\v2\n" +
	".RtcMemberR\amembers\"\xa8\x01\n" +
	"\rConverConfReq\x12\x1a\n" +
	"\bconverId\x18\x01 \x01(\tR\bconverId\x12.\n" +
	"\vchannelType\x18\x02 \x01(\x0e2\f.ChannelTypeR\vchannelType\x12\x1e\n" +
	"\n" +
	"subChannel\x18\x03 \x01(\tR\n" +
	"subChannel\x12+\n" +
	"\n" +
	"converConf\x18\x04 \x01(\v2\v.ConverConfR\n" +
	"converConfB\x1aZ\x18commons/pbdefines/pbobjsb\x06proto3"

var (
	file_commons_pbdefines_converconf_proto_rawDescOnce sync.Once
	file_commons_pbdefines_converconf_proto_rawDescData []byte
)

func file_commons_pbdefines_converconf_proto_rawDescGZIP() []byte {
	file_commons_pbdefines_converconf_proto_rawDescOnce.Do(func() {
		file_commons_pbdefines_converconf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commons_pbdefines_converconf_proto_rawDesc), len(file_commons_pbdefines_converconf_proto_rawDesc)))
	})
	return file_commons_pbdefines_converconf_proto_rawDescData
}

var file_commons_pbdefines_converconf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_commons_pbdefines_converconf_proto_goTypes = []any{
	(*ConverConf)(nil),     // 0: ConverConf
	(*ActivedRtcRoom)(nil), // 1: ActivedRtcRoom
	(*ConverConfReq)(nil),  // 2: ConverConfReq
	(RtcRoomType)(0),       // 3: RtcRoomType
	(*UserInfo)(nil),       // 4: UserInfo
	(RtcChannel)(0),        // 5: RtcChannel
	(RtcMediaType)(0),      // 6: RtcMediaType
	(*RtcMember)(nil),      // 7: RtcMember
	(ChannelType)(0),       // 8: ChannelType
}
var file_commons_pbdefines_converconf_proto_depIdxs = []int32{
	1, // 0: ConverConf.activedRtcRoom:type_name -> ActivedRtcRoom
	3, // 1: ActivedRtcRoom.roomType:type_name -> RtcRoomType
	4, // 2: ActivedRtcRoom.owner:type_name -> UserInfo
	5, // 3: ActivedRtcRoom.rtcChannel:type_name -> RtcChannel
	6, // 4: ActivedRtcRoom.rtcMediaType:type_name -> RtcMediaType
	7, // 5: ActivedRtcRoom.members:type_name -> RtcMember
	8, // 6: ConverConfReq.channelType:type_name -> ChannelType
	0, // 7: ConverConfReq.converConf:type_name -> ConverConf
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_commons_pbdefines_converconf_proto_init() }
func file_commons_pbdefines_converconf_proto_init() {
	if File_commons_pbdefines_converconf_proto != nil {
		return
	}
	file_commons_pbdefines_appmessages_proto_init()
	file_commons_pbdefines_rtcroom_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commons_pbdefines_converconf_proto_rawDesc), len(file_commons_pbdefines_converconf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_pbdefines_converconf_proto_goTypes,
		DependencyIndexes: file_commons_pbdefines_converconf_proto_depIdxs,
		MessageInfos:      file_commons_pbdefines_converconf_proto_msgTypes,
	}.Build()
	File_commons_pbdefines_converconf_proto = out.File
	file_commons_pbdefines_converconf_proto_goTypes = nil
	file_commons_pbdefines_converconf_proto_depIdxs = nil
}
