// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.3
// source: pushtoken.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_DefaultPlatform Platform = 0
	Platform_Android         Platform = 1
	Platform_iOS             Platform = 2
	Platform_Web             Platform = 3
	Platform_PC              Platform = 4
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "DefaultPlatform",
		1: "Android",
		2: "iOS",
		3: "Web",
		4: "PC",
	}
	Platform_value = map[string]int32{
		"DefaultPlatform": 0,
		"Android":         1,
		"iOS":             2,
		"Web":             3,
		"PC":              4,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_pushtoken_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_pushtoken_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_pushtoken_proto_rawDescGZIP(), []int{0}
}

type PushChannel int32

const (
	PushChannel_DefaultChannel PushChannel = 0
	PushChannel_Apple          PushChannel = 1
	PushChannel_Huawei         PushChannel = 2
	PushChannel_Xiaomi         PushChannel = 3
	PushChannel_Oppo           PushChannel = 4
	PushChannel_Vivo           PushChannel = 5
	PushChannel_FCM            PushChannel = 6
	PushChannel_JPush          PushChannel = 7
)

// Enum value maps for PushChannel.
var (
	PushChannel_name = map[int32]string{
		0: "DefaultChannel",
		1: "Apple",
		2: "Huawei",
		3: "Xiaomi",
		4: "Oppo",
		5: "Vivo",
		6: "FCM",
		7: "JPush",
	}
	PushChannel_value = map[string]int32{
		"DefaultChannel": 0,
		"Apple":          1,
		"Huawei":         2,
		"Xiaomi":         3,
		"Oppo":           4,
		"Vivo":           5,
		"FCM":            6,
		"JPush":          7,
	}
)

func (x PushChannel) Enum() *PushChannel {
	p := new(PushChannel)
	*p = x
	return p
}

func (x PushChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_pushtoken_proto_enumTypes[1].Descriptor()
}

func (PushChannel) Type() protoreflect.EnumType {
	return &file_pushtoken_proto_enumTypes[1]
}

func (x PushChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushChannel.Descriptor instead.
func (PushChannel) EnumDescriptor() ([]byte, []int) {
	return file_pushtoken_proto_rawDescGZIP(), []int{1}
}

type RegPushTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string      `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Platform    Platform    `protobuf:"varint,2,opt,name=platform,proto3,enum=Platform" json:"platform,omitempty"`
	PushChannel PushChannel `protobuf:"varint,3,opt,name=pushChannel,proto3,enum=PushChannel" json:"pushChannel,omitempty"`
	PushToken   string      `protobuf:"bytes,4,opt,name=pushToken,proto3" json:"pushToken,omitempty"`
	PackageName string      `protobuf:"bytes,5,opt,name=packageName,proto3" json:"packageName,omitempty"`
}

func (x *RegPushTokenReq) Reset() {
	*x = RegPushTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pushtoken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegPushTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegPushTokenReq) ProtoMessage() {}

func (x *RegPushTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_pushtoken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegPushTokenReq.ProtoReflect.Descriptor instead.
func (*RegPushTokenReq) Descriptor() ([]byte, []int) {
	return file_pushtoken_proto_rawDescGZIP(), []int{0}
}

func (x *RegPushTokenReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegPushTokenReq) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_DefaultPlatform
}

func (x *RegPushTokenReq) GetPushChannel() PushChannel {
	if x != nil {
		return x.PushChannel
	}
	return PushChannel_DefaultChannel
}

func (x *RegPushTokenReq) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *RegPushTokenReq) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

var File_pushtoken_proto protoreflect.FileDescriptor

var file_pushtoken_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x75, 0x73, 0x68, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x2e, 0x0a, 0x0b, 0x70, 0x75, 0x73, 0x68,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x0b, 0x70, 0x75, 0x73,
	0x68, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x46, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x6e, 0x64,
	0x72, 0x6f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x69, 0x4f, 0x53, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x43, 0x10, 0x04,
	0x2a, 0x6c, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x12, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x48, 0x75, 0x61, 0x77, 0x65, 0x69, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x58, 0x69,
	0x61, 0x6f, 0x6d, 0x69, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x70, 0x70, 0x6f, 0x10, 0x04,
	0x12, 0x08, 0x0a, 0x04, 0x56, 0x69, 0x76, 0x6f, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x43,
	0x4d, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x4a, 0x50, 0x75, 0x73, 0x68, 0x10, 0x07, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x62, 0x6f, 0x62, 0x6a, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pushtoken_proto_rawDescOnce sync.Once
	file_pushtoken_proto_rawDescData = file_pushtoken_proto_rawDesc
)

func file_pushtoken_proto_rawDescGZIP() []byte {
	file_pushtoken_proto_rawDescOnce.Do(func() {
		file_pushtoken_proto_rawDescData = protoimpl.X.CompressGZIP(file_pushtoken_proto_rawDescData)
	})
	return file_pushtoken_proto_rawDescData
}

var file_pushtoken_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pushtoken_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pushtoken_proto_goTypes = []interface{}{
	(Platform)(0),           // 0: Platform
	(PushChannel)(0),        // 1: PushChannel
	(*RegPushTokenReq)(nil), // 2: RegPushTokenReq
}
var file_pushtoken_proto_depIdxs = []int32{
	0, // 0: RegPushTokenReq.platform:type_name -> Platform
	1, // 1: RegPushTokenReq.pushChannel:type_name -> PushChannel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pushtoken_proto_init() }
func file_pushtoken_proto_init() {
	if File_pushtoken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pushtoken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegPushTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pushtoken_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pushtoken_proto_goTypes,
		DependencyIndexes: file_pushtoken_proto_depIdxs,
		EnumInfos:         file_pushtoken_proto_enumTypes,
		MessageInfos:      file_pushtoken_proto_msgTypes,
	}.Build()
	File_pushtoken_proto = out.File
	file_pushtoken_proto_rawDesc = nil
	file_pushtoken_proto_goTypes = nil
	file_pushtoken_proto_depIdxs = nil
}
