// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: commons/pbdefines/pushtoken.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_DefaultPlatform Platform = 0
	Platform_Android         Platform = 1
	Platform_iOS             Platform = 2
	Platform_Web             Platform = 3
	Platform_PC              Platform = 4
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "DefaultPlatform",
		1: "Android",
		2: "iOS",
		3: "Web",
		4: "PC",
	}
	Platform_value = map[string]int32{
		"DefaultPlatform": 0,
		"Android":         1,
		"iOS":             2,
		"Web":             3,
		"PC":              4,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_pushtoken_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_pushtoken_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_pushtoken_proto_rawDescGZIP(), []int{0}
}

type PushChannel int32

const (
	PushChannel_DefaultChannel PushChannel = 0
	PushChannel_Apple          PushChannel = 1
	PushChannel_Huawei         PushChannel = 2
	PushChannel_Xiaomi         PushChannel = 3
	PushChannel_Oppo           PushChannel = 4
	PushChannel_Vivo           PushChannel = 5
	PushChannel_FCM            PushChannel = 6
	PushChannel_JPush          PushChannel = 7
	PushChannel_Meizhu         PushChannel = 8
	PushChannel_Honor          PushChannel = 9
	PushChannel_Getui          PushChannel = 10
)

// Enum value maps for PushChannel.
var (
	PushChannel_name = map[int32]string{
		0:  "DefaultChannel",
		1:  "Apple",
		2:  "Huawei",
		3:  "Xiaomi",
		4:  "Oppo",
		5:  "Vivo",
		6:  "FCM",
		7:  "JPush",
		8:  "Meizhu",
		9:  "Honor",
		10: "Getui",
	}
	PushChannel_value = map[string]int32{
		"DefaultChannel": 0,
		"Apple":          1,
		"Huawei":         2,
		"Xiaomi":         3,
		"Oppo":           4,
		"Vivo":           5,
		"FCM":            6,
		"JPush":          7,
		"Meizhu":         8,
		"Honor":          9,
		"Getui":          10,
	}
)

func (x PushChannel) Enum() *PushChannel {
	p := new(PushChannel)
	*p = x
	return p
}

func (x PushChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_pushtoken_proto_enumTypes[1].Descriptor()
}

func (PushChannel) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_pushtoken_proto_enumTypes[1]
}

func (x PushChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushChannel.Descriptor instead.
func (PushChannel) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_pushtoken_proto_rawDescGZIP(), []int{1}
}

type RegPushTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Platform      Platform               `protobuf:"varint,2,opt,name=platform,proto3,enum=Platform" json:"platform,omitempty"`
	PushChannel   PushChannel            `protobuf:"varint,3,opt,name=pushChannel,proto3,enum=PushChannel" json:"pushChannel,omitempty"`
	PushToken     string                 `protobuf:"bytes,4,opt,name=pushToken,proto3" json:"pushToken,omitempty"`
	PackageName   string                 `protobuf:"bytes,5,opt,name=packageName,proto3" json:"packageName,omitempty"`
	VoipToken     string                 `protobuf:"bytes,6,opt,name=voipToken,proto3" json:"voipToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegPushTokenReq) Reset() {
	*x = RegPushTokenReq{}
	mi := &file_commons_pbdefines_pushtoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegPushTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegPushTokenReq) ProtoMessage() {}

func (x *RegPushTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_pushtoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegPushTokenReq.ProtoReflect.Descriptor instead.
func (*RegPushTokenReq) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_pushtoken_proto_rawDescGZIP(), []int{0}
}

func (x *RegPushTokenReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegPushTokenReq) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_DefaultPlatform
}

func (x *RegPushTokenReq) GetPushChannel() PushChannel {
	if x != nil {
		return x.PushChannel
	}
	return PushChannel_DefaultChannel
}

func (x *RegPushTokenReq) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *RegPushTokenReq) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *RegPushTokenReq) GetVoipToken() string {
	if x != nil {
		return x.VoipToken
	}
	return ""
}

var File_commons_pbdefines_pushtoken_proto protoreflect.FileDescriptor

const file_commons_pbdefines_pushtoken_proto_rawDesc = "" +
	"\n" +
	"!commons/pbdefines/pushtoken.proto\"\xe2\x01\n" +
	"\x0fRegPushTokenReq\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12%\n" +
	"\bplatform\x18\x02 \x01(\x0e2\t.PlatformR\bplatform\x12.\n" +
	"\vpushChannel\x18\x03 \x01(\x0e2\f.PushChannelR\vpushChannel\x12\x1c\n" +
	"\tpushToken\x18\x04 \x01(\tR\tpushToken\x12 \n" +
	"\vpackageName\x18\x05 \x01(\tR\vpackageName\x12\x1c\n" +
	"\tvoipToken\x18\x06 \x01(\tR\tvoipToken*F\n" +
	"\bPlatform\x12\x13\n" +
	"\x0fDefaultPlatform\x10\x00\x12\v\n" +
	"\aAndroid\x10\x01\x12\a\n" +
	"\x03iOS\x10\x02\x12\a\n" +
	"\x03Web\x10\x03\x12\x06\n" +
	"\x02PC\x10\x04*\x8e\x01\n" +
	"\vPushChannel\x12\x12\n" +
	"\x0eDefaultChannel\x10\x00\x12\t\n" +
	"\x05Apple\x10\x01\x12\n" +
	"\n" +
	"\x06Huawei\x10\x02\x12\n" +
	"\n" +
	"\x06Xiaomi\x10\x03\x12\b\n" +
	"\x04Oppo\x10\x04\x12\b\n" +
	"\x04Vivo\x10\x05\x12\a\n" +
	"\x03FCM\x10\x06\x12\t\n" +
	"\x05JPush\x10\a\x12\n" +
	"\n" +
	"\x06Meizhu\x10\b\x12\t\n" +
	"\x05Honor\x10\t\x12\t\n" +
	"\x05Getui\x10\n" +
	"B\x1aZ\x18commons/pbdefines/pbobjsb\x06proto3"

var (
	file_commons_pbdefines_pushtoken_proto_rawDescOnce sync.Once
	file_commons_pbdefines_pushtoken_proto_rawDescData []byte
)

func file_commons_pbdefines_pushtoken_proto_rawDescGZIP() []byte {
	file_commons_pbdefines_pushtoken_proto_rawDescOnce.Do(func() {
		file_commons_pbdefines_pushtoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commons_pbdefines_pushtoken_proto_rawDesc), len(file_commons_pbdefines_pushtoken_proto_rawDesc)))
	})
	return file_commons_pbdefines_pushtoken_proto_rawDescData
}

var file_commons_pbdefines_pushtoken_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_commons_pbdefines_pushtoken_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commons_pbdefines_pushtoken_proto_goTypes = []any{
	(Platform)(0),           // 0: Platform
	(PushChannel)(0),        // 1: PushChannel
	(*RegPushTokenReq)(nil), // 2: RegPushTokenReq
}
var file_commons_pbdefines_pushtoken_proto_depIdxs = []int32{
	0, // 0: RegPushTokenReq.platform:type_name -> Platform
	1, // 1: RegPushTokenReq.pushChannel:type_name -> PushChannel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_commons_pbdefines_pushtoken_proto_init() }
func file_commons_pbdefines_pushtoken_proto_init() {
	if File_commons_pbdefines_pushtoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commons_pbdefines_pushtoken_proto_rawDesc), len(file_commons_pbdefines_pushtoken_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_pbdefines_pushtoken_proto_goTypes,
		DependencyIndexes: file_commons_pbdefines_pushtoken_proto_depIdxs,
		EnumInfos:         file_commons_pbdefines_pushtoken_proto_enumTypes,
		MessageInfos:      file_commons_pbdefines_pushtoken_proto_msgTypes,
	}.Build()
	File_commons_pbdefines_pushtoken_proto = out.File
	file_commons_pbdefines_pushtoken_proto_goTypes = nil
	file_commons_pbdefines_pushtoken_proto_depIdxs = nil
}
