// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: commons/pbdefines/rtcroom.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RtcChannel int32

const (
	RtcChannel_Zego       RtcChannel = 0
	RtcChannel_LivekitRtc RtcChannel = 1
)

// Enum value maps for RtcChannel.
var (
	RtcChannel_name = map[int32]string{
		0: "Zego",
		1: "LivekitRtc",
	}
	RtcChannel_value = map[string]int32{
		"Zego":       0,
		"LivekitRtc": 1,
	}
)

func (x RtcChannel) Enum() *RtcChannel {
	p := new(RtcChannel)
	*p = x
	return p
}

func (x RtcChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtcChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[0].Descriptor()
}

func (RtcChannel) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[0]
}

func (x RtcChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtcChannel.Descriptor instead.
func (RtcChannel) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{0}
}

type RtcRoomType int32

const (
	RtcRoomType_OneOne  RtcRoomType = 0
	RtcRoomType_OneMore RtcRoomType = 1
)

// Enum value maps for RtcRoomType.
var (
	RtcRoomType_name = map[int32]string{
		0: "OneOne",
		1: "OneMore",
	}
	RtcRoomType_value = map[string]int32{
		"OneOne":  0,
		"OneMore": 1,
	}
)

func (x RtcRoomType) Enum() *RtcRoomType {
	p := new(RtcRoomType)
	*p = x
	return p
}

func (x RtcRoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtcRoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[1].Descriptor()
}

func (RtcRoomType) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[1]
}

func (x RtcRoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtcRoomType.Descriptor instead.
func (RtcRoomType) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{1}
}

type RtcState int32

const (
	RtcState_RtcStateDefault RtcState = 0
	RtcState_RtcIncoming     RtcState = 1
	RtcState_RtcOutgoing     RtcState = 2
	RtcState_RtcConnecting   RtcState = 3
	RtcState_RtcConnected    RtcState = 4
)

// Enum value maps for RtcState.
var (
	RtcState_name = map[int32]string{
		0: "RtcStateDefault",
		1: "RtcIncoming",
		2: "RtcOutgoing",
		3: "RtcConnecting",
		4: "RtcConnected",
	}
	RtcState_value = map[string]int32{
		"RtcStateDefault": 0,
		"RtcIncoming":     1,
		"RtcOutgoing":     2,
		"RtcConnecting":   3,
		"RtcConnected":    4,
	}
)

func (x RtcState) Enum() *RtcState {
	p := new(RtcState)
	*p = x
	return p
}

func (x RtcState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtcState) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[2].Descriptor()
}

func (RtcState) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[2]
}

func (x RtcState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtcState.Descriptor instead.
func (RtcState) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{2}
}

type RtcRoomEventType int32

const (
	RtcRoomEventType_DefaultRtcRoomEvent RtcRoomEventType = 0
	RtcRoomEventType_RtcJoin             RtcRoomEventType = 1
	RtcRoomEventType_RtcQuit             RtcRoomEventType = 2
	RtcRoomEventType_RtcDestroy          RtcRoomEventType = 3
	RtcRoomEventType_RtcStateChg         RtcRoomEventType = 4
)

// Enum value maps for RtcRoomEventType.
var (
	RtcRoomEventType_name = map[int32]string{
		0: "DefaultRtcRoomEvent",
		1: "RtcJoin",
		2: "RtcQuit",
		3: "RtcDestroy",
		4: "RtcStateChg",
	}
	RtcRoomEventType_value = map[string]int32{
		"DefaultRtcRoomEvent": 0,
		"RtcJoin":             1,
		"RtcQuit":             2,
		"RtcDestroy":          3,
		"RtcStateChg":         4,
	}
)

func (x RtcRoomEventType) Enum() *RtcRoomEventType {
	p := new(RtcRoomEventType)
	*p = x
	return p
}

func (x RtcRoomEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtcRoomEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[3].Descriptor()
}

func (RtcRoomEventType) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[3]
}

func (x RtcRoomEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtcRoomEventType.Descriptor instead.
func (RtcRoomEventType) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{3}
}

type RtcRoomQuitReason int32

const (
	RtcRoomQuitReason_Active      RtcRoomQuitReason = 0
	RtcRoomQuitReason_CallTimeout RtcRoomQuitReason = 1
	RtcRoomQuitReason_PingTimeout RtcRoomQuitReason = 2
)

// Enum value maps for RtcRoomQuitReason.
var (
	RtcRoomQuitReason_name = map[int32]string{
		0: "Active",
		1: "CallTimeout",
		2: "PingTimeout",
	}
	RtcRoomQuitReason_value = map[string]int32{
		"Active":      0,
		"CallTimeout": 1,
		"PingTimeout": 2,
	}
)

func (x RtcRoomQuitReason) Enum() *RtcRoomQuitReason {
	p := new(RtcRoomQuitReason)
	*p = x
	return p
}

func (x RtcRoomQuitReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtcRoomQuitReason) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[4].Descriptor()
}

func (RtcRoomQuitReason) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[4]
}

func (x RtcRoomQuitReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtcRoomQuitReason.Descriptor instead.
func (RtcRoomQuitReason) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{4}
}

type RtcMediaType int32

const (
	RtcMediaType_RtcAudio RtcMediaType = 0
	RtcMediaType_RtcVideo RtcMediaType = 1
)

// Enum value maps for RtcMediaType.
var (
	RtcMediaType_name = map[int32]string{
		0: "RtcAudio",
		1: "RtcVideo",
	}
	RtcMediaType_value = map[string]int32{
		"RtcAudio": 0,
		"RtcVideo": 1,
	}
)

func (x RtcMediaType) Enum() *RtcMediaType {
	p := new(RtcMediaType)
	*p = x
	return p
}

func (x RtcMediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RtcMediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[5].Descriptor()
}

func (RtcMediaType) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[5]
}

func (x RtcMediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RtcMediaType.Descriptor instead.
func (RtcMediaType) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{5}
}

type InviteType int32

const (
	InviteType_RtcInvite InviteType = 0
	InviteType_RtcAccept InviteType = 1
	InviteType_RtcHangup InviteType = 2
)

// Enum value maps for InviteType.
var (
	InviteType_name = map[int32]string{
		0: "RtcInvite",
		1: "RtcAccept",
		2: "RtcHangup",
	}
	InviteType_value = map[string]int32{
		"RtcInvite": 0,
		"RtcAccept": 1,
		"RtcHangup": 2,
	}
)

func (x InviteType) Enum() *InviteType {
	p := new(InviteType)
	*p = x
	return p
}

func (x InviteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteType) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_pbdefines_rtcroom_proto_enumTypes[6].Descriptor()
}

func (InviteType) Type() protoreflect.EnumType {
	return &file_commons_pbdefines_rtcroom_proto_enumTypes[6]
}

func (x InviteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteType.Descriptor instead.
func (InviteType) EnumDescriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{6}
}

type RtcRoomReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomType       RtcRoomType            `protobuf:"varint,1,opt,name=roomType,proto3,enum=RtcRoomType" json:"roomType,omitempty"`
	RoomId         string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	JoinMember     *RtcMember             `protobuf:"bytes,3,opt,name=joinMember,proto3" json:"joinMember,omitempty"`
	RtcChannel     RtcChannel             `protobuf:"varint,4,opt,name=rtcChannel,proto3,enum=RtcChannel" json:"rtcChannel,omitempty"`
	RtcMediaType   RtcMediaType           `protobuf:"varint,5,opt,name=rtcMediaType,proto3,enum=RtcMediaType" json:"rtcMediaType,omitempty"`
	Ext            string                 `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	AttachedConver *ConverIndex           `protobuf:"bytes,7,opt,name=attachedConver,proto3" json:"attachedConver,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RtcRoomReq) Reset() {
	*x = RtcRoomReq{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcRoomReq) ProtoMessage() {}

func (x *RtcRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcRoomReq.ProtoReflect.Descriptor instead.
func (*RtcRoomReq) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{0}
}

func (x *RtcRoomReq) GetRoomType() RtcRoomType {
	if x != nil {
		return x.RoomType
	}
	return RtcRoomType_OneOne
}

func (x *RtcRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RtcRoomReq) GetJoinMember() *RtcMember {
	if x != nil {
		return x.JoinMember
	}
	return nil
}

func (x *RtcRoomReq) GetRtcChannel() RtcChannel {
	if x != nil {
		return x.RtcChannel
	}
	return RtcChannel_Zego
}

func (x *RtcRoomReq) GetRtcMediaType() RtcMediaType {
	if x != nil {
		return x.RtcMediaType
	}
	return RtcMediaType_RtcAudio
}

func (x *RtcRoomReq) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *RtcRoomReq) GetAttachedConver() *ConverIndex {
	if x != nil {
		return x.AttachedConver
	}
	return nil
}

type RtcRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomType      RtcRoomType            `protobuf:"varint,1,opt,name=roomType,proto3,enum=RtcRoomType" json:"roomType,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Owner         *UserInfo              `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	RtcChannel    RtcChannel             `protobuf:"varint,4,opt,name=rtcChannel,proto3,enum=RtcChannel" json:"rtcChannel,omitempty"`
	RtcMediaType  RtcMediaType           `protobuf:"varint,5,opt,name=rtcMediaType,proto3,enum=RtcMediaType" json:"rtcMediaType,omitempty"`
	Ext           string                 `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	Auth          *RtcAuth               `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	Members       []*RtcMember           `protobuf:"bytes,51,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcRoom) Reset() {
	*x = RtcRoom{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcRoom) ProtoMessage() {}

func (x *RtcRoom) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcRoom.ProtoReflect.Descriptor instead.
func (*RtcRoom) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{1}
}

func (x *RtcRoom) GetRoomType() RtcRoomType {
	if x != nil {
		return x.RoomType
	}
	return RtcRoomType_OneOne
}

func (x *RtcRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RtcRoom) GetOwner() *UserInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *RtcRoom) GetRtcChannel() RtcChannel {
	if x != nil {
		return x.RtcChannel
	}
	return RtcChannel_Zego
}

func (x *RtcRoom) GetRtcMediaType() RtcMediaType {
	if x != nil {
		return x.RtcMediaType
	}
	return RtcMediaType_RtcAudio
}

func (x *RtcRoom) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *RtcRoom) GetAuth() *RtcAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *RtcRoom) GetMembers() []*RtcMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type RtcMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *UserInfo              `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	RtcState      RtcState               `protobuf:"varint,2,opt,name=rtcState,proto3,enum=RtcState" json:"rtcState,omitempty"`
	CallTime      int64                  `protobuf:"varint,3,opt,name=callTime,proto3" json:"callTime,omitempty"`
	ConnectTime   int64                  `protobuf:"varint,4,opt,name=connectTime,proto3" json:"connectTime,omitempty"`
	HangupTime    int64                  `protobuf:"varint,5,opt,name=hangupTime,proto3" json:"hangupTime,omitempty"`
	Inviter       *UserInfo              `protobuf:"bytes,6,opt,name=inviter,proto3" json:"inviter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcMember) Reset() {
	*x = RtcMember{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcMember) ProtoMessage() {}

func (x *RtcMember) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcMember.ProtoReflect.Descriptor instead.
func (*RtcMember) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{2}
}

func (x *RtcMember) GetMember() *UserInfo {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *RtcMember) GetRtcState() RtcState {
	if x != nil {
		return x.RtcState
	}
	return RtcState_RtcStateDefault
}

func (x *RtcMember) GetCallTime() int64 {
	if x != nil {
		return x.CallTime
	}
	return 0
}

func (x *RtcMember) GetConnectTime() int64 {
	if x != nil {
		return x.ConnectTime
	}
	return 0
}

func (x *RtcMember) GetHangupTime() int64 {
	if x != nil {
		return x.HangupTime
	}
	return 0
}

func (x *RtcMember) GetInviter() *UserInfo {
	if x != nil {
		return x.Inviter
	}
	return nil
}

type MemberState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomType      RtcRoomType            `protobuf:"varint,2,opt,name=roomType,proto3,enum=RtcRoomType" json:"roomType,omitempty"`
	MemberId      string                 `protobuf:"bytes,3,opt,name=memberId,proto3" json:"memberId,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	RtcState      RtcState               `protobuf:"varint,5,opt,name=rtcState,proto3,enum=RtcState" json:"rtcState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberState) Reset() {
	*x = MemberState{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberState) ProtoMessage() {}

func (x *MemberState) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberState.ProtoReflect.Descriptor instead.
func (*MemberState) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{3}
}

func (x *MemberState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MemberState) GetRoomType() RtcRoomType {
	if x != nil {
		return x.RoomType
	}
	return RtcRoomType_OneOne
}

func (x *MemberState) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *MemberState) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MemberState) GetRtcState() RtcState {
	if x != nil {
		return x.RtcState
	}
	return RtcState_RtcStateDefault
}

type SyncMemberStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDelete      bool                   `protobuf:"varint,1,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	Member        *MemberState           `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMemberStateReq) Reset() {
	*x = SyncMemberStateReq{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMemberStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMemberStateReq) ProtoMessage() {}

func (x *SyncMemberStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMemberStateReq.ProtoReflect.Descriptor instead.
func (*SyncMemberStateReq) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{4}
}

func (x *SyncMemberStateReq) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *SyncMemberStateReq) GetMember() *MemberState {
	if x != nil {
		return x.Member
	}
	return nil
}

type RtcRoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomEventType RtcRoomEventType       `protobuf:"varint,1,opt,name=roomEventType,proto3,enum=RtcRoomEventType" json:"roomEventType,omitempty"`
	Members       []*RtcMember           `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Room          *RtcRoom               `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Reason        RtcRoomQuitReason      `protobuf:"varint,4,opt,name=reason,proto3,enum=RtcRoomQuitReason" json:"reason,omitempty"`
	EventTime     int64                  `protobuf:"varint,5,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcRoomEvent) Reset() {
	*x = RtcRoomEvent{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcRoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcRoomEvent) ProtoMessage() {}

func (x *RtcRoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcRoomEvent.ProtoReflect.Descriptor instead.
func (*RtcRoomEvent) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{5}
}

func (x *RtcRoomEvent) GetRoomEventType() RtcRoomEventType {
	if x != nil {
		return x.RoomEventType
	}
	return RtcRoomEventType_DefaultRtcRoomEvent
}

func (x *RtcRoomEvent) GetMembers() []*RtcMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RtcRoomEvent) GetRoom() *RtcRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RtcRoomEvent) GetReason() RtcRoomQuitReason {
	if x != nil {
		return x.Reason
	}
	return RtcRoomQuitReason_Active
}

func (x *RtcRoomEvent) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type RtcInviteReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetIds      []string               `protobuf:"bytes,1,rep,name=targetIds,proto3" json:"targetIds,omitempty"`
	RoomType       RtcRoomType            `protobuf:"varint,2,opt,name=roomType,proto3,enum=RtcRoomType" json:"roomType,omitempty"`
	RoomId         string                 `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RtcChannel     RtcChannel             `protobuf:"varint,4,opt,name=rtcChannel,proto3,enum=RtcChannel" json:"rtcChannel,omitempty"`
	RtcMediaType   RtcMediaType           `protobuf:"varint,5,opt,name=rtcMediaType,proto3,enum=RtcMediaType" json:"rtcMediaType,omitempty"`
	Ext            string                 `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	AttachedConver *ConverIndex           `protobuf:"bytes,7,opt,name=attachedConver,proto3" json:"attachedConver,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RtcInviteReq) Reset() {
	*x = RtcInviteReq{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcInviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcInviteReq) ProtoMessage() {}

func (x *RtcInviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcInviteReq.ProtoReflect.Descriptor instead.
func (*RtcInviteReq) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{6}
}

func (x *RtcInviteReq) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *RtcInviteReq) GetRoomType() RtcRoomType {
	if x != nil {
		return x.RoomType
	}
	return RtcRoomType_OneOne
}

func (x *RtcInviteReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RtcInviteReq) GetRtcChannel() RtcChannel {
	if x != nil {
		return x.RtcChannel
	}
	return RtcChannel_Zego
}

func (x *RtcInviteReq) GetRtcMediaType() RtcMediaType {
	if x != nil {
		return x.RtcMediaType
	}
	return RtcMediaType_RtcAudio
}

func (x *RtcInviteReq) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *RtcInviteReq) GetAttachedConver() *ConverIndex {
	if x != nil {
		return x.AttachedConver
	}
	return nil
}

type RtcMemberRooms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RtcMemberRoom       `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcMemberRooms) Reset() {
	*x = RtcMemberRooms{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcMemberRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcMemberRooms) ProtoMessage() {}

func (x *RtcMemberRooms) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcMemberRooms.ProtoReflect.Descriptor instead.
func (*RtcMemberRooms) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{7}
}

func (x *RtcMemberRooms) GetRooms() []*RtcMemberRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type RtcMemberRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomType      RtcRoomType            `protobuf:"varint,1,opt,name=roomType,proto3,enum=RtcRoomType" json:"roomType,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Owner         *UserInfo              `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	RtcState      RtcState               `protobuf:"varint,4,opt,name=rtcState,proto3,enum=RtcState" json:"rtcState,omitempty"`
	RtcChannel    RtcChannel             `protobuf:"varint,5,opt,name=rtcChannel,proto3,enum=RtcChannel" json:"rtcChannel,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	RtcMediaType  RtcMediaType           `protobuf:"varint,7,opt,name=rtcMediaType,proto3,enum=RtcMediaType" json:"rtcMediaType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcMemberRoom) Reset() {
	*x = RtcMemberRoom{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcMemberRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcMemberRoom) ProtoMessage() {}

func (x *RtcMemberRoom) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcMemberRoom.ProtoReflect.Descriptor instead.
func (*RtcMemberRoom) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{8}
}

func (x *RtcMemberRoom) GetRoomType() RtcRoomType {
	if x != nil {
		return x.RoomType
	}
	return RtcRoomType_OneOne
}

func (x *RtcMemberRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RtcMemberRoom) GetOwner() *UserInfo {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *RtcMemberRoom) GetRtcState() RtcState {
	if x != nil {
		return x.RtcState
	}
	return RtcState_RtcStateDefault
}

func (x *RtcMemberRoom) GetRtcChannel() RtcChannel {
	if x != nil {
		return x.RtcChannel
	}
	return RtcChannel_Zego
}

func (x *RtcMemberRoom) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RtcMemberRoom) GetRtcMediaType() RtcMediaType {
	if x != nil {
		return x.RtcMediaType
	}
	return RtcMediaType_RtcAudio
}

type RtcAuth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZegoAuth       *ZegoAuth              `protobuf:"bytes,1,opt,name=zegoAuth,proto3" json:"zegoAuth,omitempty"`
	LivekitRtcAuth *LivekitRtcAuth        `protobuf:"bytes,2,opt,name=livekitRtcAuth,proto3" json:"livekitRtcAuth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RtcAuth) Reset() {
	*x = RtcAuth{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcAuth) ProtoMessage() {}

func (x *RtcAuth) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcAuth.ProtoReflect.Descriptor instead.
func (*RtcAuth) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{9}
}

func (x *RtcAuth) GetZegoAuth() *ZegoAuth {
	if x != nil {
		return x.ZegoAuth
	}
	return nil
}

func (x *RtcAuth) GetLivekitRtcAuth() *LivekitRtcAuth {
	if x != nil {
		return x.LivekitRtcAuth
	}
	return nil
}

type ZegoAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZegoAuth) Reset() {
	*x = ZegoAuth{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZegoAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZegoAuth) ProtoMessage() {}

func (x *ZegoAuth) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZegoAuth.ProtoReflect.Descriptor instead.
func (*ZegoAuth) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{10}
}

func (x *ZegoAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LivekitRtcAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ServiceUrl    string                 `protobuf:"bytes,2,opt,name=serviceUrl,proto3" json:"serviceUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivekitRtcAuth) Reset() {
	*x = LivekitRtcAuth{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivekitRtcAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivekitRtcAuth) ProtoMessage() {}

func (x *LivekitRtcAuth) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivekitRtcAuth.ProtoReflect.Descriptor instead.
func (*LivekitRtcAuth) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{11}
}

func (x *LivekitRtcAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LivekitRtcAuth) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

type RtcInviteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteType    InviteType             `protobuf:"varint,1,opt,name=inviteType,proto3,enum=InviteType" json:"inviteType,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Room          *RtcRoom               `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	TargetUsers   []*UserInfo            `protobuf:"bytes,4,rep,name=targetUsers,proto3" json:"targetUsers,omitempty"`
	EventTime     int64                  `protobuf:"varint,5,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcInviteEvent) Reset() {
	*x = RtcInviteEvent{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcInviteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcInviteEvent) ProtoMessage() {}

func (x *RtcInviteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcInviteEvent.ProtoReflect.Descriptor instead.
func (*RtcInviteEvent) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{12}
}

func (x *RtcInviteEvent) GetInviteType() InviteType {
	if x != nil {
		return x.InviteType
	}
	return InviteType_RtcInvite
}

func (x *RtcInviteEvent) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RtcInviteEvent) GetRoom() *RtcRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RtcInviteEvent) GetTargetUsers() []*UserInfo {
	if x != nil {
		return x.TargetUsers
	}
	return nil
}

func (x *RtcInviteEvent) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type RtcAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcAnswer) Reset() {
	*x = RtcAnswer{}
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcAnswer) ProtoMessage() {}

func (x *RtcAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_rtcroom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcAnswer.ProtoReflect.Descriptor instead.
func (*RtcAnswer) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_rtcroom_proto_rawDescGZIP(), []int{13}
}

func (x *RtcAnswer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_commons_pbdefines_rtcroom_proto protoreflect.FileDescriptor

const file_commons_pbdefines_rtcroom_proto_rawDesc = "" +
	"\n" +
	"\x1fcommons/pbdefines/rtcroom.proto\x1a#commons/pbdefines/appmessages.proto\"\xa2\x02\n" +
	"\n" +
	"RtcRoomReq\x12(\n" +
	"\broomType\x18\x01 \x01(\x0e2\f.RtcRoomTypeR\broomType\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12*\n" +
	"\n" +
	"joinMember\x18\x03 \x01(\v2\n" +
	".RtcMemberR\n" +
	"joinMember\x12+\n" +
	"\n" +
	"rtcChannel\x18\x04 \x01(\x0e2\v.RtcChannelR\n" +
	"rtcChannel\x121\n" +
	"\frtcMediaType\x18\x05 \x01(\x0e2\r.RtcMediaTypeR\frtcMediaType\x12\x10\n" +
	"\x03ext\x18\x06 \x01(\tR\x03ext\x124\n" +
	"\x0eattachedConver\x18\a \x01(\v2\f.ConverIndexR\x0eattachedConver\"\xa2\x02\n" +
	"\aRtcRoom\x12(\n" +
	"\broomType\x18\x01 \x01(\x0e2\f.RtcRoomTypeR\broomType\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\x05owner\x18\x03 \x01(\v2\t.UserInfoR\x05owner\x12+\n" +
	"\n" +
	"rtcChannel\x18\x04 \x01(\x0e2\v.RtcChannelR\n" +
	"rtcChannel\x121\n" +
	"\frtcMediaType\x18\x05 \x01(\x0e2\r.RtcMediaTypeR\frtcMediaType\x12\x10\n" +
	"\x03ext\x18\x06 \x01(\tR\x03ext\x12\x1c\n" +
	"\x04auth\x18\a \x01(\v2\b.RtcAuthR\x04auth\x12$\n" +
	"\amembers\x183 \x03(\v2\n" +
	".RtcMemberR\amembers\"\xd8\x01\n" +
	"\tRtcMember\x12!\n" +
	"\x06member\x18\x01 \x01(\v2\t.UserInfoR\x06member\x12%\n" +
	"\brtcState\x18\x02 \x01(\x0e2\t.RtcStateR\brtcState\x12\x1a\n" +
	"\bcallTime\x18\x03 \x01(\x03R\bcallTime\x12 \n" +
	"\vconnectTime\x18\x04 \x01(\x03R\vconnectTime\x12\x1e\n" +
	"\n" +
	"hangupTime\x18\x05 \x01(\x03R\n" +
	"hangupTime\x12#\n" +
	"\ainviter\x18\x06 \x01(\v2\t.UserInfoR\ainviter\"\xae\x01\n" +
	"\vMemberState\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12(\n" +
	"\broomType\x18\x02 \x01(\x0e2\f.RtcRoomTypeR\broomType\x12\x1a\n" +
	"\bmemberId\x18\x03 \x01(\tR\bmemberId\x12\x1a\n" +
	"\bdeviceId\x18\x04 \x01(\tR\bdeviceId\x12%\n" +
	"\brtcState\x18\x05 \x01(\x0e2\t.RtcStateR\brtcState\"V\n" +
	"\x12SyncMemberStateReq\x12\x1a\n" +
	"\bisDelete\x18\x01 \x01(\bR\bisDelete\x12$\n" +
	"\x06member\x18\x02 \x01(\v2\f.MemberStateR\x06member\"\xd5\x01\n" +
	"\fRtcRoomEvent\x127\n" +
	"\rroomEventType\x18\x01 \x01(\x0e2\x11.RtcRoomEventTypeR\rroomEventType\x12$\n" +
	"\amembers\x18\x02 \x03(\v2\n" +
	".RtcMemberR\amembers\x12\x1c\n" +
	"\x04room\x18\x03 \x01(\v2\b.RtcRoomR\x04room\x12*\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x12.RtcRoomQuitReasonR\x06reason\x12\x1c\n" +
	"\teventTime\x18\x05 \x01(\x03R\teventTime\"\x96\x02\n" +
	"\fRtcInviteReq\x12\x1c\n" +
	"\ttargetIds\x18\x01 \x03(\tR\ttargetIds\x12(\n" +
	"\broomType\x18\x02 \x01(\x0e2\f.RtcRoomTypeR\broomType\x12\x16\n" +
	"\x06roomId\x18\x03 \x01(\tR\x06roomId\x12+\n" +
	"\n" +
	"rtcChannel\x18\x04 \x01(\x0e2\v.RtcChannelR\n" +
	"rtcChannel\x121\n" +
	"\frtcMediaType\x18\x05 \x01(\x0e2\r.RtcMediaTypeR\frtcMediaType\x12\x10\n" +
	"\x03ext\x18\x06 \x01(\tR\x03ext\x124\n" +
	"\x0eattachedConver\x18\a \x01(\v2\f.ConverIndexR\x0eattachedConver\"6\n" +
	"\x0eRtcMemberRooms\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.RtcMemberRoomR\x05rooms\"\x95\x02\n" +
	"\rRtcMemberRoom\x12(\n" +
	"\broomType\x18\x01 \x01(\x0e2\f.RtcRoomTypeR\broomType\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\tR\x06roomId\x12\x1f\n" +
	"\x05owner\x18\x03 \x01(\v2\t.UserInfoR\x05owner\x12%\n" +
	"\brtcState\x18\x04 \x01(\x0e2\t.RtcStateR\brtcState\x12+\n" +
	"\n" +
	"rtcChannel\x18\x05 \x01(\x0e2\v.RtcChannelR\n" +
	"rtcChannel\x12\x1a\n" +
	"\bdeviceId\x18\x06 \x01(\tR\bdeviceId\x121\n" +
	"\frtcMediaType\x18\a \x01(\x0e2\r.RtcMediaTypeR\frtcMediaType\"i\n" +
	"\aRtcAuth\x12%\n" +
	"\bzegoAuth\x18\x01 \x01(\v2\t.ZegoAuthR\bzegoAuth\x127\n" +
	"\x0elivekitRtcAuth\x18\x02 \x01(\v2\x0f.LivekitRtcAuthR\x0elivekitRtcAuth\" \n" +
	"\bZegoAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"F\n" +
	"\x0eLivekitRtcAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"serviceUrl\x18\x02 \x01(\tR\n" +
	"serviceUrl\"\xc5\x01\n" +
	"\x0eRtcInviteEvent\x12+\n" +
	"\n" +
	"inviteType\x18\x01 \x01(\x0e2\v.InviteTypeR\n" +
	"inviteType\x12\x1d\n" +
	"\x04user\x18\x02 \x01(\v2\t.UserInfoR\x04user\x12\x1c\n" +
	"\x04room\x18\x03 \x01(\v2\b.RtcRoomR\x04room\x12+\n" +
	"\vtargetUsers\x18\x04 \x03(\v2\t.UserInfoR\vtargetUsers\x12\x1c\n" +
	"\teventTime\x18\x05 \x01(\x03R\teventTime\"#\n" +
	"\tRtcAnswer\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId*&\n" +
	"\n" +
	"RtcChannel\x12\b\n" +
	"\x04Zego\x10\x00\x12\x0e\n" +
	"\n" +
	"LivekitRtc\x10\x01*&\n" +
	"\vRtcRoomType\x12\n" +
	"\n" +
	"\x06OneOne\x10\x00\x12\v\n" +
	"\aOneMore\x10\x01*f\n" +
	"\bRtcState\x12\x13\n" +
	"\x0fRtcStateDefault\x10\x00\x12\x0f\n" +
	"\vRtcIncoming\x10\x01\x12\x0f\n" +
	"\vRtcOutgoing\x10\x02\x12\x11\n" +
	"\rRtcConnecting\x10\x03\x12\x10\n" +
	"\fRtcConnected\x10\x04*f\n" +
	"\x10RtcRoomEventType\x12\x17\n" +
	"\x13DefaultRtcRoomEvent\x10\x00\x12\v\n" +
	"\aRtcJoin\x10\x01\x12\v\n" +
	"\aRtcQuit\x10\x02\x12\x0e\n" +
	"\n" +
	"RtcDestroy\x10\x03\x12\x0f\n" +
	"\vRtcStateChg\x10\x04*A\n" +
	"\x11RtcRoomQuitReason\x12\n" +
	"\n" +
	"\x06Active\x10\x00\x12\x0f\n" +
	"\vCallTimeout\x10\x01\x12\x0f\n" +
	"\vPingTimeout\x10\x02**\n" +
	"\fRtcMediaType\x12\f\n" +
	"\bRtcAudio\x10\x00\x12\f\n" +
	"\bRtcVideo\x10\x01*9\n" +
	"\n" +
	"InviteType\x12\r\n" +
	"\tRtcInvite\x10\x00\x12\r\n" +
	"\tRtcAccept\x10\x01\x12\r\n" +
	"\tRtcHangup\x10\x02B\x1aZ\x18commons/pbdefines/pbobjsb\x06proto3"

var (
	file_commons_pbdefines_rtcroom_proto_rawDescOnce sync.Once
	file_commons_pbdefines_rtcroom_proto_rawDescData []byte
)

func file_commons_pbdefines_rtcroom_proto_rawDescGZIP() []byte {
	file_commons_pbdefines_rtcroom_proto_rawDescOnce.Do(func() {
		file_commons_pbdefines_rtcroom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commons_pbdefines_rtcroom_proto_rawDesc), len(file_commons_pbdefines_rtcroom_proto_rawDesc)))
	})
	return file_commons_pbdefines_rtcroom_proto_rawDescData
}

var file_commons_pbdefines_rtcroom_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_commons_pbdefines_rtcroom_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_commons_pbdefines_rtcroom_proto_goTypes = []any{
	(RtcChannel)(0),            // 0: RtcChannel
	(RtcRoomType)(0),           // 1: RtcRoomType
	(RtcState)(0),              // 2: RtcState
	(RtcRoomEventType)(0),      // 3: RtcRoomEventType
	(RtcRoomQuitReason)(0),     // 4: RtcRoomQuitReason
	(RtcMediaType)(0),          // 5: RtcMediaType
	(InviteType)(0),            // 6: InviteType
	(*RtcRoomReq)(nil),         // 7: RtcRoomReq
	(*RtcRoom)(nil),            // 8: RtcRoom
	(*RtcMember)(nil),          // 9: RtcMember
	(*MemberState)(nil),        // 10: MemberState
	(*SyncMemberStateReq)(nil), // 11: SyncMemberStateReq
	(*RtcRoomEvent)(nil),       // 12: RtcRoomEvent
	(*RtcInviteReq)(nil),       // 13: RtcInviteReq
	(*RtcMemberRooms)(nil),     // 14: RtcMemberRooms
	(*RtcMemberRoom)(nil),      // 15: RtcMemberRoom
	(*RtcAuth)(nil),            // 16: RtcAuth
	(*ZegoAuth)(nil),           // 17: ZegoAuth
	(*LivekitRtcAuth)(nil),     // 18: LivekitRtcAuth
	(*RtcInviteEvent)(nil),     // 19: RtcInviteEvent
	(*RtcAnswer)(nil),          // 20: RtcAnswer
	(*ConverIndex)(nil),        // 21: ConverIndex
	(*UserInfo)(nil),           // 22: UserInfo
}
var file_commons_pbdefines_rtcroom_proto_depIdxs = []int32{
	1,  // 0: RtcRoomReq.roomType:type_name -> RtcRoomType
	9,  // 1: RtcRoomReq.joinMember:type_name -> RtcMember
	0,  // 2: RtcRoomReq.rtcChannel:type_name -> RtcChannel
	5,  // 3: RtcRoomReq.rtcMediaType:type_name -> RtcMediaType
	21, // 4: RtcRoomReq.attachedConver:type_name -> ConverIndex
	1,  // 5: RtcRoom.roomType:type_name -> RtcRoomType
	22, // 6: RtcRoom.owner:type_name -> UserInfo
	0,  // 7: RtcRoom.rtcChannel:type_name -> RtcChannel
	5,  // 8: RtcRoom.rtcMediaType:type_name -> RtcMediaType
	16, // 9: RtcRoom.auth:type_name -> RtcAuth
	9,  // 10: RtcRoom.members:type_name -> RtcMember
	22, // 11: RtcMember.member:type_name -> UserInfo
	2,  // 12: RtcMember.rtcState:type_name -> RtcState
	22, // 13: RtcMember.inviter:type_name -> UserInfo
	1,  // 14: MemberState.roomType:type_name -> RtcRoomType
	2,  // 15: MemberState.rtcState:type_name -> RtcState
	10, // 16: SyncMemberStateReq.member:type_name -> MemberState
	3,  // 17: RtcRoomEvent.roomEventType:type_name -> RtcRoomEventType
	9,  // 18: RtcRoomEvent.members:type_name -> RtcMember
	8,  // 19: RtcRoomEvent.room:type_name -> RtcRoom
	4,  // 20: RtcRoomEvent.reason:type_name -> RtcRoomQuitReason
	1,  // 21: RtcInviteReq.roomType:type_name -> RtcRoomType
	0,  // 22: RtcInviteReq.rtcChannel:type_name -> RtcChannel
	5,  // 23: RtcInviteReq.rtcMediaType:type_name -> RtcMediaType
	21, // 24: RtcInviteReq.attachedConver:type_name -> ConverIndex
	15, // 25: RtcMemberRooms.rooms:type_name -> RtcMemberRoom
	1,  // 26: RtcMemberRoom.roomType:type_name -> RtcRoomType
	22, // 27: RtcMemberRoom.owner:type_name -> UserInfo
	2,  // 28: RtcMemberRoom.rtcState:type_name -> RtcState
	0,  // 29: RtcMemberRoom.rtcChannel:type_name -> RtcChannel
	5,  // 30: RtcMemberRoom.rtcMediaType:type_name -> RtcMediaType
	17, // 31: RtcAuth.zegoAuth:type_name -> ZegoAuth
	18, // 32: RtcAuth.livekitRtcAuth:type_name -> LivekitRtcAuth
	6,  // 33: RtcInviteEvent.inviteType:type_name -> InviteType
	22, // 34: RtcInviteEvent.user:type_name -> UserInfo
	8,  // 35: RtcInviteEvent.room:type_name -> RtcRoom
	22, // 36: RtcInviteEvent.targetUsers:type_name -> UserInfo
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_commons_pbdefines_rtcroom_proto_init() }
func file_commons_pbdefines_rtcroom_proto_init() {
	if File_commons_pbdefines_rtcroom_proto != nil {
		return
	}
	file_commons_pbdefines_appmessages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commons_pbdefines_rtcroom_proto_rawDesc), len(file_commons_pbdefines_rtcroom_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_pbdefines_rtcroom_proto_goTypes,
		DependencyIndexes: file_commons_pbdefines_rtcroom_proto_depIdxs,
		EnumInfos:         file_commons_pbdefines_rtcroom_proto_enumTypes,
		MessageInfos:      file_commons_pbdefines_rtcroom_proto_msgTypes,
	}.Build()
	File_commons_pbdefines_rtcroom_proto = out.File
	file_commons_pbdefines_rtcroom_proto_goTypes = nil
	file_commons_pbdefines_rtcroom_proto_depIdxs = nil
}
