// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: commons/pbdefines/tokens.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenWrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TokenValue    []byte                 `protobuf:"bytes,3,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenWrap) Reset() {
	*x = TokenWrap{}
	mi := &file_commons_pbdefines_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenWrap) ProtoMessage() {}

func (x *TokenWrap) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenWrap.ProtoReflect.Descriptor instead.
func (*TokenWrap) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *TokenWrap) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *TokenWrap) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TokenWrap) GetTokenValue() []byte {
	if x != nil {
		return x.TokenValue
	}
	return nil
}

type TokenValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	TokenTime     int64                  `protobuf:"varint,3,opt,name=tokenTime,proto3" json:"tokenTime,omitempty"`
	UserType      UserType               `protobuf:"varint,4,opt,name=userType,proto3,enum=UserType" json:"userType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValue) Reset() {
	*x = TokenValue{}
	mi := &file_commons_pbdefines_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValue) ProtoMessage() {}

func (x *TokenValue) ProtoReflect() protoreflect.Message {
	mi := &file_commons_pbdefines_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValue.ProtoReflect.Descriptor instead.
func (*TokenValue) Descriptor() ([]byte, []int) {
	return file_commons_pbdefines_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *TokenValue) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenValue) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TokenValue) GetTokenTime() int64 {
	if x != nil {
		return x.TokenTime
	}
	return 0
}

func (x *TokenValue) GetUserType() UserType {
	if x != nil {
		return x.UserType
	}
	return UserType_User
}

var File_commons_pbdefines_tokens_proto protoreflect.FileDescriptor

const file_commons_pbdefines_tokens_proto_rawDesc = "" +
	"\n" +
	"\x1ecommons/pbdefines/tokens.proto\x1a#commons/pbdefines/appmessages.proto\"]\n" +
	"\tTokenWrap\x12\x16\n" +
	"\x06appKey\x18\x01 \x01(\tR\x06appKey\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1e\n" +
	"\n" +
	"tokenValue\x18\x03 \x01(\fR\n" +
	"tokenValue\"\x85\x01\n" +
	"\n" +
	"TokenValue\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\ttokenTime\x18\x03 \x01(\x03R\ttokenTime\x12%\n" +
	"\buserType\x18\x04 \x01(\x0e2\t.UserTypeR\buserTypeB\x1aZ\x18commons/pbdefines/pbobjsb\x06proto3"

var (
	file_commons_pbdefines_tokens_proto_rawDescOnce sync.Once
	file_commons_pbdefines_tokens_proto_rawDescData []byte
)

func file_commons_pbdefines_tokens_proto_rawDescGZIP() []byte {
	file_commons_pbdefines_tokens_proto_rawDescOnce.Do(func() {
		file_commons_pbdefines_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commons_pbdefines_tokens_proto_rawDesc), len(file_commons_pbdefines_tokens_proto_rawDesc)))
	})
	return file_commons_pbdefines_tokens_proto_rawDescData
}

var file_commons_pbdefines_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_commons_pbdefines_tokens_proto_goTypes = []any{
	(*TokenWrap)(nil),  // 0: TokenWrap
	(*TokenValue)(nil), // 1: TokenValue
	(UserType)(0),      // 2: UserType
}
var file_commons_pbdefines_tokens_proto_depIdxs = []int32{
	2, // 0: TokenValue.userType:type_name -> UserType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commons_pbdefines_tokens_proto_init() }
func file_commons_pbdefines_tokens_proto_init() {
	if File_commons_pbdefines_tokens_proto != nil {
		return
	}
	file_commons_pbdefines_appmessages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commons_pbdefines_tokens_proto_rawDesc), len(file_commons_pbdefines_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_pbdefines_tokens_proto_goTypes,
		DependencyIndexes: file_commons_pbdefines_tokens_proto_depIdxs,
		MessageInfos:      file_commons_pbdefines_tokens_proto_msgTypes,
	}.Build()
	File_commons_pbdefines_tokens_proto = out.File
	file_commons_pbdefines_tokens_proto_goTypes = nil
	file_commons_pbdefines_tokens_proto_depIdxs = nil
}
