// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: connect.proto

package codec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectMsgBody struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProtoId    string                 `protobuf:"bytes,1,opt,name=protoId,proto3" json:"protoId,omitempty"`
	SdkVersion string                 `protobuf:"bytes,2,opt,name=sdkVersion,proto3" json:"sdkVersion,omitempty"` //sdk 版本
	Appkey     string                 `protobuf:"bytes,3,opt,name=appkey,proto3" json:"appkey,omitempty"`
	Token      string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	// 设备信息
	DeviceId        string `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Platform        string `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`               //iOS/Android/iPad
	DeviceCompany   string `protobuf:"bytes,7,opt,name=deviceCompany,proto3" json:"deviceCompany,omitempty"`     //设备厂商, huawei/apple
	DeviceModel     string `protobuf:"bytes,8,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`         //设备型号  例如: iPhone8
	DeviceOsVersion string `protobuf:"bytes,9,opt,name=deviceOsVersion,proto3" json:"deviceOsVersion,omitempty"` //手机操作系统版本
	PushToken       string `protobuf:"bytes,10,opt,name=pushToken,proto3" json:"pushToken,omitempty"`            //厂商推送Token
	// 网络
	NetworkId     string `protobuf:"bytes,11,opt,name=networkId,proto3" json:"networkId,omitempty"`         //网络类型；4G/wifi
	IspNum        string `protobuf:"bytes,12,opt,name=isp_num,json=ispNum,proto3" json:"isp_num,omitempty"` //网络运营商编号
	ClientIp      string `protobuf:"bytes,13,opt,name=clientIp,proto3" json:"clientIp,omitempty"`
	PackageName   string `protobuf:"bytes,14,opt,name=packageName,proto3" json:"packageName,omitempty"`
	PushChannel   string `protobuf:"bytes,15,opt,name=pushChannel,proto3" json:"pushChannel,omitempty"`
	Ext           string `protobuf:"bytes,16,opt,name=ext,proto3" json:"ext,omitempty"`
	InstanceId    string `protobuf:"bytes,17,opt,name=instanceId,proto3" json:"instanceId,omitempty"` //客户端实例标识,用于多开时识别不同的实例，clientSession
	Language      string `protobuf:"bytes,18,opt,name=language,proto3" json:"language,omitempty"`     //语言设置
	IsBackend     bool   `protobuf:"varint,19,opt,name=isBackend,proto3" json:"isBackend,omitempty"`  //app是否在后台
	VoipToken     string `protobuf:"bytes,20,opt,name=voipToken,proto3" json:"voipToken,omitempty"`   // voip token of iOS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectMsgBody) Reset() {
	*x = ConnectMsgBody{}
	mi := &file_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectMsgBody) ProtoMessage() {}

func (x *ConnectMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectMsgBody.ProtoReflect.Descriptor instead.
func (*ConnectMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectMsgBody) GetProtoId() string {
	if x != nil {
		return x.ProtoId
	}
	return ""
}

func (x *ConnectMsgBody) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ConnectMsgBody) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *ConnectMsgBody) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnectMsgBody) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectMsgBody) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ConnectMsgBody) GetDeviceCompany() string {
	if x != nil {
		return x.DeviceCompany
	}
	return ""
}

func (x *ConnectMsgBody) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *ConnectMsgBody) GetDeviceOsVersion() string {
	if x != nil {
		return x.DeviceOsVersion
	}
	return ""
}

func (x *ConnectMsgBody) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *ConnectMsgBody) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ConnectMsgBody) GetIspNum() string {
	if x != nil {
		return x.IspNum
	}
	return ""
}

func (x *ConnectMsgBody) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ConnectMsgBody) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ConnectMsgBody) GetPushChannel() string {
	if x != nil {
		return x.PushChannel
	}
	return ""
}

func (x *ConnectMsgBody) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ConnectMsgBody) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ConnectMsgBody) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ConnectMsgBody) GetIsBackend() bool {
	if x != nil {
		return x.IsBackend
	}
	return false
}

func (x *ConnectMsgBody) GetVoipToken() string {
	if x != nil {
		return x.VoipToken
	}
	return ""
}

type ConnectAckMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Session       string                 `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ext           string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
	Conf          *ConnectConf           `protobuf:"bytes,6,opt,name=conf,proto3" json:"conf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectAckMsgBody) Reset() {
	*x = ConnectAckMsgBody{}
	mi := &file_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectAckMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAckMsgBody) ProtoMessage() {}

func (x *ConnectAckMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAckMsgBody.ProtoReflect.Descriptor instead.
func (*ConnectAckMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectAckMsgBody) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConnectAckMsgBody) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectAckMsgBody) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ConnectAckMsgBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConnectAckMsgBody) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ConnectAckMsgBody) GetConf() *ConnectConf {
	if x != nil {
		return x.Conf
	}
	return nil
}

type ConnectConf struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatInterval int32                  `protobuf:"varint,1,opt,name=heartbeatInterval,proto3" json:"heartbeatInterval,omitempty"`
	HeartbeatTimeout  int32                  `protobuf:"varint,2,opt,name=heartbeatTimeout,proto3" json:"heartbeatTimeout,omitempty"`
	SignalTimeout     int32                  `protobuf:"varint,3,opt,name=signalTimeout,proto3" json:"signalTimeout,omitempty"`
	SignalFailCount   int32                  `protobuf:"varint,4,opt,name=signalFailCount,proto3" json:"signalFailCount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectConf) Reset() {
	*x = ConnectConf{}
	mi := &file_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectConf) ProtoMessage() {}

func (x *ConnectConf) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectConf.ProtoReflect.Descriptor instead.
func (*ConnectConf) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectConf) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *ConnectConf) GetHeartbeatTimeout() int32 {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return 0
}

func (x *ConnectConf) GetSignalTimeout() int32 {
	if x != nil {
		return x.SignalTimeout
	}
	return 0
}

func (x *ConnectConf) GetSignalFailCount() int32 {
	if x != nil {
		return x.SignalFailCount
	}
	return 0
}

type DisconnectMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ext           string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectMsgBody) Reset() {
	*x = DisconnectMsgBody{}
	mi := &file_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMsgBody) ProtoMessage() {}

func (x *DisconnectMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMsgBody.ProtoReflect.Descriptor instead.
func (*DisconnectMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectMsgBody) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DisconnectMsgBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DisconnectMsgBody) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

type PublishMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMsgBody) Reset() {
	*x = PublishMsgBody{}
	mi := &file_connect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMsgBody) ProtoMessage() {}

func (x *PublishMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMsgBody.ProtoReflect.Descriptor instead.
func (*PublishMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{4}
}

func (x *PublishMsgBody) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PublishMsgBody) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMsgBody) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *PublishMsgBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PublishMsgBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishAckMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MsgSeqNo      int64                  `protobuf:"varint,5,opt,name=msgSeqNo,proto3" json:"msgSeqNo,omitempty"`
	MemberCount   int32                  `protobuf:"varint,6,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,7,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	ModifiedMsg   *SimplifiedDownMsg     `protobuf:"bytes,8,opt,name=modifiedMsg,proto3" json:"modifiedMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAckMsgBody) Reset() {
	*x = PublishAckMsgBody{}
	mi := &file_connect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAckMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAckMsgBody) ProtoMessage() {}

func (x *PublishAckMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAckMsgBody.ProtoReflect.Descriptor instead.
func (*PublishAckMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{5}
}

func (x *PublishAckMsgBody) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PublishAckMsgBody) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PublishAckMsgBody) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PublishAckMsgBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PublishAckMsgBody) GetMsgSeqNo() int64 {
	if x != nil {
		return x.MsgSeqNo
	}
	return 0
}

func (x *PublishAckMsgBody) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *PublishAckMsgBody) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *PublishAckMsgBody) GetModifiedMsg() *SimplifiedDownMsg {
	if x != nil {
		return x.ModifiedMsg
	}
	return nil
}

type SimplifiedDownMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,3,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgContent    []byte                 `protobuf:"bytes,7,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimplifiedDownMsg) Reset() {
	*x = SimplifiedDownMsg{}
	mi := &file_connect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplifiedDownMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplifiedDownMsg) ProtoMessage() {}

func (x *SimplifiedDownMsg) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplifiedDownMsg.ProtoReflect.Descriptor instead.
func (*SimplifiedDownMsg) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{6}
}

func (x *SimplifiedDownMsg) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *SimplifiedDownMsg) GetMsgContent() []byte {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

type QueryMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMsgBody) Reset() {
	*x = QueryMsgBody{}
	mi := &file_connect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMsgBody) ProtoMessage() {}

func (x *QueryMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMsgBody.ProtoReflect.Descriptor instead.
func (*QueryMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{7}
}

func (x *QueryMsgBody) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *QueryMsgBody) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *QueryMsgBody) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *QueryMsgBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueryMsgBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryAckMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAckMsgBody) Reset() {
	*x = QueryAckMsgBody{}
	mi := &file_connect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAckMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAckMsgBody) ProtoMessage() {}

func (x *QueryAckMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAckMsgBody.ProtoReflect.Descriptor instead.
func (*QueryAckMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{8}
}

func (x *QueryAckMsgBody) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *QueryAckMsgBody) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryAckMsgBody) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueryAckMsgBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryConfirmMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConfirmMsgBody) Reset() {
	*x = QueryConfirmMsgBody{}
	mi := &file_connect_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfirmMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfirmMsgBody) ProtoMessage() {}

func (x *QueryConfirmMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfirmMsgBody.ProtoReflect.Descriptor instead.
func (*QueryConfirmMsgBody) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{9}
}

func (x *QueryConfirmMsgBody) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ImWebsocketMsg struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Cmd     int32                  `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Qos     int32                  `protobuf:"varint,3,opt,name=qos,proto3" json:"qos,omitempty"`
	Payload []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Types that are valid to be assigned to Testof:
	//
	//	*ImWebsocketMsg_ConnectMsgBody
	//	*ImWebsocketMsg_ConnectAckMsgBody
	//	*ImWebsocketMsg_DisconnectMsgBody
	//	*ImWebsocketMsg_PublishMsgBody
	//	*ImWebsocketMsg_PubAckMsgBody
	//	*ImWebsocketMsg_QryMsgBody
	//	*ImWebsocketMsg_QryAckMsgBody
	//	*ImWebsocketMsg_QryConfirmMsgBody
	Testof        isImWebsocketMsg_Testof `protobuf_oneof:"testof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImWebsocketMsg) Reset() {
	*x = ImWebsocketMsg{}
	mi := &file_connect_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImWebsocketMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImWebsocketMsg) ProtoMessage() {}

func (x *ImWebsocketMsg) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImWebsocketMsg.ProtoReflect.Descriptor instead.
func (*ImWebsocketMsg) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{10}
}

func (x *ImWebsocketMsg) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ImWebsocketMsg) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *ImWebsocketMsg) GetQos() int32 {
	if x != nil {
		return x.Qos
	}
	return 0
}

func (x *ImWebsocketMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ImWebsocketMsg) GetTestof() isImWebsocketMsg_Testof {
	if x != nil {
		return x.Testof
	}
	return nil
}

func (x *ImWebsocketMsg) GetConnectMsgBody() *ConnectMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_ConnectMsgBody); ok {
			return x.ConnectMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetConnectAckMsgBody() *ConnectAckMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_ConnectAckMsgBody); ok {
			return x.ConnectAckMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetDisconnectMsgBody() *DisconnectMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_DisconnectMsgBody); ok {
			return x.DisconnectMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetPublishMsgBody() *PublishMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_PublishMsgBody); ok {
			return x.PublishMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetPubAckMsgBody() *PublishAckMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_PubAckMsgBody); ok {
			return x.PubAckMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetQryMsgBody() *QueryMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_QryMsgBody); ok {
			return x.QryMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetQryAckMsgBody() *QueryAckMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_QryAckMsgBody); ok {
			return x.QryAckMsgBody
		}
	}
	return nil
}

func (x *ImWebsocketMsg) GetQryConfirmMsgBody() *QueryConfirmMsgBody {
	if x != nil {
		if x, ok := x.Testof.(*ImWebsocketMsg_QryConfirmMsgBody); ok {
			return x.QryConfirmMsgBody
		}
	}
	return nil
}

type isImWebsocketMsg_Testof interface {
	isImWebsocketMsg_Testof()
}

type ImWebsocketMsg_ConnectMsgBody struct {
	ConnectMsgBody *ConnectMsgBody `protobuf:"bytes,11,opt,name=connectMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_ConnectAckMsgBody struct {
	ConnectAckMsgBody *ConnectAckMsgBody `protobuf:"bytes,12,opt,name=ConnectAckMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_DisconnectMsgBody struct {
	DisconnectMsgBody *DisconnectMsgBody `protobuf:"bytes,13,opt,name=disconnectMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_PublishMsgBody struct {
	PublishMsgBody *PublishMsgBody `protobuf:"bytes,14,opt,name=publishMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_PubAckMsgBody struct {
	PubAckMsgBody *PublishAckMsgBody `protobuf:"bytes,15,opt,name=pubAckMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_QryMsgBody struct {
	QryMsgBody *QueryMsgBody `protobuf:"bytes,16,opt,name=qryMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_QryAckMsgBody struct {
	QryAckMsgBody *QueryAckMsgBody `protobuf:"bytes,17,opt,name=qryAckMsgBody,proto3,oneof"`
}

type ImWebsocketMsg_QryConfirmMsgBody struct {
	QryConfirmMsgBody *QueryConfirmMsgBody `protobuf:"bytes,18,opt,name=qryConfirmMsgBody,proto3,oneof"`
}

func (*ImWebsocketMsg_ConnectMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_ConnectAckMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_DisconnectMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_PublishMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_PubAckMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_QryMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_QryAckMsgBody) isImWebsocketMsg_Testof() {}

func (*ImWebsocketMsg_QryConfirmMsgBody) isImWebsocketMsg_Testof() {}

var File_connect_proto protoreflect.FileDescriptor

const file_connect_proto_rawDesc = "" +
	"\n" +
	"\rconnect.proto\"\xe1\x04\n" +
	"\x0eConnectMsgBody\x12\x18\n" +
	"\aprotoId\x18\x01 \x01(\tR\aprotoId\x12\x1e\n" +
	"\n" +
	"sdkVersion\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\x16\n" +
	"\x06appkey\x18\x03 \x01(\tR\x06appkey\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1a\n" +
	"\bdeviceId\x18\x05 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12$\n" +
	"\rdeviceCompany\x18\a \x01(\tR\rdeviceCompany\x12 \n" +
	"\vdeviceModel\x18\b \x01(\tR\vdeviceModel\x12(\n" +
	"\x0fdeviceOsVersion\x18\t \x01(\tR\x0fdeviceOsVersion\x12\x1c\n" +
	"\tpushToken\x18\n" +
	" \x01(\tR\tpushToken\x12\x1c\n" +
	"\tnetworkId\x18\v \x01(\tR\tnetworkId\x12\x17\n" +
	"\aisp_num\x18\f \x01(\tR\x06ispNum\x12\x1a\n" +
	"\bclientIp\x18\r \x01(\tR\bclientIp\x12 \n" +
	"\vpackageName\x18\x0e \x01(\tR\vpackageName\x12 \n" +
	"\vpushChannel\x18\x0f \x01(\tR\vpushChannel\x12\x10\n" +
	"\x03ext\x18\x10 \x01(\tR\x03ext\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x11 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\blanguage\x18\x12 \x01(\tR\blanguage\x12\x1c\n" +
	"\tisBackend\x18\x13 \x01(\bR\tisBackend\x12\x1c\n" +
	"\tvoipToken\x18\x14 \x01(\tR\tvoipToken\"\xab\x01\n" +
	"\x11ConnectAckMsgBody\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\asession\x18\x03 \x01(\tR\asession\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12 \n" +
	"\x04conf\x18\x06 \x01(\v2\f.ConnectConfR\x04conf\"\xb7\x01\n" +
	"\vConnectConf\x12,\n" +
	"\x11heartbeatInterval\x18\x01 \x01(\x05R\x11heartbeatInterval\x12*\n" +
	"\x10heartbeatTimeout\x18\x02 \x01(\x05R\x10heartbeatTimeout\x12$\n" +
	"\rsignalTimeout\x18\x03 \x01(\x05R\rsignalTimeout\x12(\n" +
	"\x0fsignalFailCount\x18\x04 \x01(\x05R\x0fsignalFailCount\"W\n" +
	"\x11DisconnectMsgBody\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\"\x8a\x01\n" +
	"\x0ePublishMsgBody\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\tR\btargetId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"\x87\x02\n" +
	"\x11PublishAckMsgBody\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x14\n" +
	"\x05msgId\x18\x03 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bmsgSeqNo\x18\x05 \x01(\x03R\bmsgSeqNo\x12 \n" +
	"\vmemberCount\x18\x06 \x01(\x05R\vmemberCount\x12 \n" +
	"\vclientMsgId\x18\a \x01(\tR\vclientMsgId\x124\n" +
	"\vmodifiedMsg\x18\b \x01(\v2\x12.SimplifiedDownMsgR\vmodifiedMsg\"M\n" +
	"\x11SimplifiedDownMsg\x12\x18\n" +
	"\amsgType\x18\x03 \x01(\tR\amsgType\x12\x1e\n" +
	"\n" +
	"msgContent\x18\a \x01(\fR\n" +
	"msgContent\"\x88\x01\n" +
	"\fQueryMsgBody\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\tR\btargetId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"m\n" +
	"\x0fQueryAckMsgBody\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"+\n" +
	"\x13QueryConfirmMsgBody\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"\xdd\x04\n" +
	"\x0eImWebsocketMsg\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\x05R\x03cmd\x12\x10\n" +
	"\x03qos\x18\x03 \x01(\x05R\x03qos\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x129\n" +
	"\x0econnectMsgBody\x18\v \x01(\v2\x0f.ConnectMsgBodyH\x00R\x0econnectMsgBody\x12B\n" +
	"\x11ConnectAckMsgBody\x18\f \x01(\v2\x12.ConnectAckMsgBodyH\x00R\x11ConnectAckMsgBody\x12B\n" +
	"\x11disconnectMsgBody\x18\r \x01(\v2\x12.DisconnectMsgBodyH\x00R\x11disconnectMsgBody\x129\n" +
	"\x0epublishMsgBody\x18\x0e \x01(\v2\x0f.PublishMsgBodyH\x00R\x0epublishMsgBody\x12:\n" +
	"\rpubAckMsgBody\x18\x0f \x01(\v2\x12.PublishAckMsgBodyH\x00R\rpubAckMsgBody\x12/\n" +
	"\n" +
	"qryMsgBody\x18\x10 \x01(\v2\r.QueryMsgBodyH\x00R\n" +
	"qryMsgBody\x128\n" +
	"\rqryAckMsgBody\x18\x11 \x01(\v2\x10.QueryAckMsgBodyH\x00R\rqryAckMsgBody\x12D\n" +
	"\x11qryConfirmMsgBody\x18\x12 \x01(\v2\x14.QueryConfirmMsgBodyH\x00R\x11qryConfirmMsgBodyB\b\n" +
	"\x06testofB\tZ\a./codecb\x06proto3"

var (
	file_connect_proto_rawDescOnce sync.Once
	file_connect_proto_rawDescData []byte
)

func file_connect_proto_rawDescGZIP() []byte {
	file_connect_proto_rawDescOnce.Do(func() {
		file_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)))
	})
	return file_connect_proto_rawDescData
}

var file_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_connect_proto_goTypes = []any{
	(*ConnectMsgBody)(nil),      // 0: ConnectMsgBody
	(*ConnectAckMsgBody)(nil),   // 1: ConnectAckMsgBody
	(*ConnectConf)(nil),         // 2: ConnectConf
	(*DisconnectMsgBody)(nil),   // 3: DisconnectMsgBody
	(*PublishMsgBody)(nil),      // 4: PublishMsgBody
	(*PublishAckMsgBody)(nil),   // 5: PublishAckMsgBody
	(*SimplifiedDownMsg)(nil),   // 6: SimplifiedDownMsg
	(*QueryMsgBody)(nil),        // 7: QueryMsgBody
	(*QueryAckMsgBody)(nil),     // 8: QueryAckMsgBody
	(*QueryConfirmMsgBody)(nil), // 9: QueryConfirmMsgBody
	(*ImWebsocketMsg)(nil),      // 10: ImWebsocketMsg
}
var file_connect_proto_depIdxs = []int32{
	2,  // 0: ConnectAckMsgBody.conf:type_name -> ConnectConf
	6,  // 1: PublishAckMsgBody.modifiedMsg:type_name -> SimplifiedDownMsg
	0,  // 2: ImWebsocketMsg.connectMsgBody:type_name -> ConnectMsgBody
	1,  // 3: ImWebsocketMsg.ConnectAckMsgBody:type_name -> ConnectAckMsgBody
	3,  // 4: ImWebsocketMsg.disconnectMsgBody:type_name -> DisconnectMsgBody
	4,  // 5: ImWebsocketMsg.publishMsgBody:type_name -> PublishMsgBody
	5,  // 6: ImWebsocketMsg.pubAckMsgBody:type_name -> PublishAckMsgBody
	7,  // 7: ImWebsocketMsg.qryMsgBody:type_name -> QueryMsgBody
	8,  // 8: ImWebsocketMsg.qryAckMsgBody:type_name -> QueryAckMsgBody
	9,  // 9: ImWebsocketMsg.qryConfirmMsgBody:type_name -> QueryConfirmMsgBody
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_connect_proto_init() }
func file_connect_proto_init() {
	if File_connect_proto != nil {
		return
	}
	file_connect_proto_msgTypes[10].OneofWrappers = []any{
		(*ImWebsocketMsg_ConnectMsgBody)(nil),
		(*ImWebsocketMsg_ConnectAckMsgBody)(nil),
		(*ImWebsocketMsg_DisconnectMsgBody)(nil),
		(*ImWebsocketMsg_PublishMsgBody)(nil),
		(*ImWebsocketMsg_PubAckMsgBody)(nil),
		(*ImWebsocketMsg_QryMsgBody)(nil),
		(*ImWebsocketMsg_QryAckMsgBody)(nil),
		(*ImWebsocketMsg_QryConfirmMsgBody)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_proto_goTypes,
		DependencyIndexes: file_connect_proto_depIdxs,
		MessageInfos:      file_connect_proto_msgTypes,
	}.Build()
	File_connect_proto = out.File
	file_connect_proto_goTypes = nil
	file_connect_proto_depIdxs = nil
}
