nodeName: {{ POD_NAME }}
nodeHost: {{ POD_IP }}
msgStoreEngine: {{ MSG_STORE_ENGINE }}

log:
  logPath: ./logs
  logName: jim-info

kvdb:
  isOpen: true

mysql:
  user: root
  password: {{ MYSQL_ROOT_PASSWORD }}
  address: {{ MYSQL_ADDR }}
  name: {{ MYSQL_DB_NAME }}

mongodb:
  address: root:{{ MONGODB_ROOT_PASSWORD }}@{{ MONGODB_ADDR }}:27017
  name: jim_msgs

connectManager:
  wsPort: {{ WS_PORT }}

apiGateway:
  httpPort: {{ API_HTTP_PORT }}

navGateway:
  httpPort: {{ NAV_HTTP_PORT }}

adminGateway:
  httpPort: {{ ADMIN_HTTP_PORT }}

imApiDomain: http://127.0.0.1:{{ API_HTTP_PORT }}